name = "second-brain-mcp"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# R2 bucket bindings
[[r2_buckets]]
binding = "SECOND_BRAIN_BUCKET"
bucket_name = "second-brain-storage"

# KV namespace bindings
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "96dc84c8c72141e998c004cbab2fc695"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "40096f26b84842c3a160501230ca74ca"

# Analytics Engine binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "second-brain-analytics"

# Durable Objects binding
[[durable_objects.bindings]]
name = "MCP_SESSIONS"
class_name = "MCPSessionDurableObject"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["MCPSessionDurableObject"]

# Cron triggers for daily backup
[triggers]
crons = ["0 2 * * *"]

# Observability - Workers Logs
[observability]
enabled = true
head_sampling_rate = 1.0  # 100% sampling

# Environment variables (set via wrangler secret)
# GITHUB_CLIENT_ID - GitHub OAuth app client ID
# GITHUB_CLIENT_SECRET - GitHub OAuth app client secret
# GITHUB_ALLOWED_USER_ID - Authorized GitHub user ID
# COOKIE_ENCRYPTION_KEY - Encryption key for OAuth tokens
# AWS_ACCESS_KEY_ID - AWS S3 backup access key
# AWS_SECRET_ACCESS_KEY - AWS S3 backup secret key
# AWS_REGION - AWS S3 region
# AWS_S3_BACKUP_BUCKET - AWS S3 backup bucket name

[env.development]
name = "second-brain-mcp-dev"

[[env.development.r2_buckets]]
binding = "SECOND_BRAIN_BUCKET"
bucket_name = "second-brain-storage-dev"

[[env.development.kv_namespaces]]
binding = "OAUTH_KV"
id = "b39b7475acd0425ab46881ab1d701226"

[[env.development.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "6f08a90245f34ff5afc335a3105a57d3"
