name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@9.0.0 --activate

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type check
        run: pnpm run type-check

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@9.0.0 --activate

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@9.0.0 --activate

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test -- --coverage --ci --silent

      - name: Check coverage thresholds
        run: |
          STATEMENTS=$(cat coverage/coverage-summary.json | jq '.total.statements.pct')
          FUNCTIONS=$(cat coverage/coverage-summary.json | jq '.total.functions.pct')
          echo "Statement coverage: $STATEMENTS%"
          echo "Function coverage: $FUNCTIONS%"
          if (( $(echo "$STATEMENTS < 95" | bc -l) )); then
            echo "❌ Statement coverage ($STATEMENTS%) is below 95% threshold"
            exit 1
          fi
          if (( $(echo "$FUNCTIONS < 95" | bc -l) )); then
            echo "❌ Function coverage ($FUNCTIONS%) is below 95% threshold"
            exit 1
          fi
          echo "✅ Coverage thresholds met"

      - name: Report code coverage
        uses: clearlyip/code-coverage-report-action@v5
        id: coverage
        continue-on-error: true  # Don't fail yet - check for override first
        if: always()
        with:
          filename: 'coverage/clover.xml'
          badge: true
          fail_on_negative_difference: true
          only_list_changed_files: true  # Only show coverage for changed files in PRs
          # No overall_coverage_fail_threshold - use trend-based monitoring only

      - name: Check coverage override
        if: steps.coverage.outcome == 'failure' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            // Coverage decreased - check for override comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const overridePattern = /coverage-override:\s*(.+)/i;
            const overrideComment = comments.find(c => overridePattern.test(c.body));

            if (overrideComment) {
              const match = overrideComment.body.match(overridePattern);
              const reason = match ? match[1].trim() : 'No reason provided';
              core.warning(`Coverage decrease approved: ${reason}`);
              core.notice('⚠️ Coverage decreased but override approved by maintainer');
              core.notice(`Override comment: ${overrideComment.html_url}`);
            } else {
              core.setFailed('❌ Coverage decreased. Add comment "coverage-override: <reason>" to approve.');
              core.error('Coverage regressions require explicit approval.');
              core.error('Add a PR comment: coverage-override: <explanation>');
            }

      - name: Fail if coverage decreased without override
        if: steps.coverage.outcome == 'failure' && github.event_name != 'pull_request'
        run: |
          echo "❌ Coverage decreased on direct push to main"
          echo "This should not happen - all changes should go through PRs"
          exit 1

      - name: Post coverage comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && always()
        with:
          header: coverage
          path: ${{ steps.coverage.outputs.file }}

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@9.0.0 --activate

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run E2E tests
        run: pnpm run test:e2e
